version: '3.8'

services:
  postgres:
    image: joshuasundance/postgis_pgvector:1.0.0
    container_name: postgres
    env_file:
      - .env
    volumes:
      - govgis_nov2023-slim-spatial-server_pgdata:/var/lib/postgresql/data
    networks:
      - govgis_nov2023-slim-spatial-server
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]


  pgadmin:
    image: dpage/pgadmin4:7.8
    container_name: pgadmin
    env_file:
      - .env
    volumes:
      - govgis_nov2023-slim-spatial-server_pgadmin_data:/var/lib/pgadmin
    networks:
      - govgis_nov2023-slim-spatial-server
    ports:
      - "${PGADMIN_PORT:-80}:80"


volumes:
  govgis_nov2023-slim-spatial-server_pgdata:
  govgis_nov2023-slim-spatial-server_pgadmin_data:

networks:
  govgis_nov2023-slim-spatial-server:
    driver: bridge
